apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        name: hello-world
    spec:
      containers:
        - name:  hello-world
          image: 172.29.66.98:30002/demo/hello-world:${env.BUILD_NUMBER}
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31290
  selector:
    name: hello-world
  type: NodePort